### ISSUE TITLE
Crashes Robofont when not online.

### ISSUE THREAD

**Issue by frankrolf** [jackjennings/Mechanic#14]
Robofont will hang on startup when there is no active internet connection (e.g. in the train).
The only solution is temporarily de-activating Mechanic.

**Comment by jackjennings** [comment]
Hmm… I thought that checking for updates in a new thread would allow Robofont to continue starting up in the mean time. @typemytype is this not the case, or could that have changed at some point?

**Comment by typemytype** [comment]
mm, pure python threads and cocoa objects are not working that well together, especially when popup UI elements from that thread. 

In my experience its more stable to use NSThread 
see the Batch extension as example https://github.com/typemytype/batchRoboFontExtension/blob/master/Batch.roboFontExt/lib/batchTools.py#L57

hope this helps...

**Comment by jackjennings** [comment]
Yeah, that does. Looks like I'll need to rewrite my threading code to use something similar.

**Comment by jackjennings** [comment]
Released the update as version 1.0.5
