### ISSUE TITLE
Couldn't get information about extension

### ISSUE THREAD

**Issue by jenskutilek** [jackjennings/Mechanic#5]
When I start RoboFont, I always get this message:

Couldn't get information about UFO Cleaner.roboFontExt from jenskutilek/RoboFont

Is it because there is a space character in the extension file name?

**Comment by jackjennings** [comment]
@jenskutilek with the release of 1.0 I think that these issues should become a lot less frequent. I've cleaned up the system that pulls information off of github, and removed some of the code branches that might have been accidentally triggered. I'm going to close this, but if you see the error again, please go ahead an reopen this issue.
